### PR TITLE
Cors things innit

### PR DESCRIPTION
**Pull request by ahldr**

### CODE REVIEW

**Comment by mildlyincompetent** [comment]
ack

**Comment by mildlyincompetent** [comment]
bepis

**Comment by mildlyincompetent** [comment]
colgate

**Comment by mildlyincompetent** [comment]
obamids

**Comment by mildlyincompetent** [comment]
dc

**Comment by mildlyincompetent** [comment]
boing

**Comment by ahldr** [comment]
730 MAX BOIS

**Comment by mildlyincompetent** [comment]
bat

**Comment by mildlyincompetent** [comment]
uhoh

**Comment by ahldr** [comment]
bush

**Comment by mildlyincompetent** [comment]
bzz

**Pull request merged**
